services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      - FLASK_ENV=production
      - JWT_SECRET_KEY=SUA_CHAVE_AQUI
      - SECRET_KEY=SUA_SECRET_KEY
      - DATABASE_URL=sqlite:///intranet.db
    volumes:
      - sqlite_data:/app/instance
    networks:
      - intranet-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    # SEM ports: aqui — o Coolify injeta via proxy
    depends_on:
      - backend
    networks:
      - intranet-net
