version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - FLASK_ENV=production
      - JWT_SECRET_KEY=61df3d4880dabb76e3fa7db84351935e1dad6000edad1df20c3a064f3cda8e7d

    volumes:
      - sqlite_data:/app/instance

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1247:1247"
    depends_on:
      - backend

volumes:
  sqlite_data:
